version: "3.1"
services:
  # api:
  #   image: app_image
  #   container_name: api
  #   restart: always
  #   env_file:
  #     - .env.docker
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #     - mongodb
  #     - clickhouse
  #   networks:
  #     - postgres
  #     - mongodb_net
  #     - clickhouse-network

  # nginx:
  #   build: ./docker/nginx
  #   container_name: nginx_server
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
  #   depends_on:
  #     - api
 
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5439:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-for-kip
    image: dpage/pgadmin4:7.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5059:80"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    networks:
      - mongodb_net
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongodb
    networks:
      - mongodb_net
    ports:
      - 3300:3000
  
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./docker/clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./docker/clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - clickhouse-network
 
  dbeaver:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "3301:8978"
    volumes:
      - local_dbeaver:/var/cloudbeaver/workspace:/opt/cloudbeaver/workspace 
    networks:
      - clickhouse-network
      
 

volumes:
  postgres:
  pgadmin:
  data: {}

  local_dbeaver:  {}


networks:
  postgres:
    driver: bridge
  mongodb_net:
    driver: bridge
    ipam:
      driver: default
  clickhouse-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16 
