"""Fixed typo in operation

Revision ID: f7addc347efa
Revises: 7b423f8654e8
Create Date: 2023-03-20 00:46:56.398298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7addc347efa'
down_revision = '7b423f8654e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_table', sa.Column('date', sa.TIMESTAMP(), nullable=False))
    op.drop_column('operation_table', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_table', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('operation_table', 'date')
    # ### end Alembic commands ###
