"""Removed enum type

Revision ID: b2f1d9529aa6
Revises: f7addc347efa
Create Date: 2023-03-20 00:48:13.670548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2f1d9529aa6'
down_revision = 'f7addc347efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_table', 'insatrument_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_table', sa.Column('insatrument_type', postgresql.ENUM('instrument1', 'instrument2', 'instrument3', name='instrumenttype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
