"""Add auto increment

Revision ID: 4bb43491538f
Revises: b2f1d9529aa6
Create Date: 2023-03-20 01:48:28.121814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb43491538f'
down_revision = 'b2f1d9529aa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
