"""Initial revision

Revision ID: 31762d9f023b
Revises: 
Create Date: 2023-06-01 13:50:06.003067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31762d9f023b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
