"""fixed_typo

Revision ID: 49fa3654f18e
Revises: 5fcf6c8f4531
Create Date: 2023-06-01 14:13:45.766533

"""
from alembic import op
import sqlalchemy as sa
import clickhouse_sqlalchemy

# revision identifiers, used by Alembic.
revision = '49fa3654f18e'
down_revision = '5fcf6c8f4531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column(
        'created_at', clickhouse_sqlalchemy.types.common.Date(), nullable=False))
    op.drop_column('events', 'created_ad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column(
        'created_ad', clickhouse_sqlalchemy.types.common.Date(), nullable=False))
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
