"""initial_commit

Revision ID: 466e78fb47f1
Revises: 
Create Date: 2023-06-04 20:54:59.439657

"""
from alembic import op
import sqlalchemy as sa
import clickhouse_sqlalchemy

# revision identifiers, used by Alembic.
revision = '466e78fb47f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column(
        'action', clickhouse_sqlalchemy.types.common.String(), nullable=False))
    op.add_column('events', sa.Column(
        'created_at', clickhouse_sqlalchemy.types.common.DateTime(), nullable=False))
    op.add_column('events', sa.Column(
        'created_by', clickhouse_sqlalchemy.types.common.UUID(), nullable=False))
    op.add_column('events', sa.Column(
        'device_id', clickhouse_sqlalchemy.types.common.UUID(), nullable=False))
    op.add_column('events', sa.Column('responsible_person',
                  clickhouse_sqlalchemy.types.common.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'responsible_person')
    op.drop_column('events', 'device_id')
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'action')
    # ### end Alembic commands ###
