"""add_fields_on_events

Revision ID: 5fcf6c8f4531
Revises: 31762d9f023b
Create Date: 2023-06-01 14:11:08.882006

"""
from alembic import op
import sqlalchemy as sa
import clickhouse_sqlalchemy


# revision identifiers, used by Alembic.
revision = '5fcf6c8f4531'
down_revision = '31762d9f023b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column(
        'action', clickhouse_sqlalchemy.types.common.String(), nullable=False))
    op.add_column('events', sa.Column(
        'created_ad', clickhouse_sqlalchemy.types.common.Date(), nullable=False))
    op.add_column('events', sa.Column(
        'created_by', clickhouse_sqlalchemy.types.common.UUID(), nullable=False))
    op.add_column('events', sa.Column(
        'device_id', clickhouse_sqlalchemy.types.common.UUID(), nullable=False))
    op.add_column('events', sa.Column('responsible_person',
                  clickhouse_sqlalchemy.types.common.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'responsible_person')
    op.drop_column('events', 'device_id')
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'created_ad')
    op.drop_column('events', 'action')
    # ### end Alembic commands ###
