"""Add operations

Revision ID: b833b8cae2bc
Revises: c27065dae05f
Create Date: 2023-03-20 00:19:31.941223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b833b8cae2bc'
down_revision = 'c27065dae05f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('insatrument_type', sa.Enum('instrument1', 'instrument2', 'instrument3', name='instrumenttype'), nullable=False),
    sa.Column('data', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_table')
    # ### end Alembic commands ###
