"""Add some data

Revision ID: be04bb99f663
Revises: 9bba277a4726
Create Date: 2023-03-19 22:52:40.134516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be04bb99f663'
down_revision = '9bba277a4726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
